export const mockedOwnerData = {
    login: "custom_owner_login",
    id: 3,
    node_id: "node_id_3",
    avatar_url: "https://example.com/custom_owner_avatar",
    gravatar_id: "custom_gravatar_id",
    url: "https://example.com/custom_owner",
    html_url: "https://example.com/custom_owner/profile",
    followers_url: "https://example.com/custom_owner/followers",
    following_url: "https://example.com/custom_owner/following",
    gists_url: "https://example.com/custom_owner/gists",
    starred_url: "https://example.com/custom_owner/starred",
    subscriptions_url: "https://example.com/custom_owner/subscriptions",
    organizations_url: "https://example.com/custom_owner/orgs",
    repos_url: "https://example.com/custom_owner/repos",
    events_url: "https://example.com/custom_owner/events",
    received_events_url: "https://example.com/custom_owner/received_events",
    type: "Custom Owner Type",
    site_admin: true,
  };

export const mockRepoData = [
    {
      id: 1,
      node_id: "node_id_1",
      name: "example_repo",
      full_name: "Example Repo",
      private: false,
      owner: mockedOwnerData,
      html_url: "https://example.com/repo",
      description: "Custom description",
      fork: false,
      url: "https://example.com/api/repo",
      forks_url: "https://example.com/api/repo/forks",
      keys_url: "https://example.com/api/repo/keys",
      collaborators_url: "https://example.com/api/repo/collaborators",
      teams_url: "https://example.com/api/repo/teams",
      hooks_url: "https://example.com/api/repo/hooks",
      issue_events_url: "https://example.com/api/repo/issues/events",
      events_url: "https://example.com/api/repo/events",
      assignees_url: "https://example.com/api/repo/assignees",
      branches_url: "https://example.com/api/repo/branches",
      tags_url: "https://example.com/api/repo/tags",
      blobs_url: "https://example.com/api/repo/blobs",
      git_tags_url: "https://example.com/api/repo/git/tags",
      git_refs_url: "https://example.com/api/repo/git/refs",
      trees_url: "https://example.com/api/repo/trees",
      statuses_url: "https://example.com/api/repo/statuses",
      languages_url: "https://example.com/api/repo/languages",
      stargazers_url: "https://example.com/api/repo/stargazers",
      contributors_url: "https://example.com/api/repo/contributors",
      subscribers_url: "https://example.com/api/repo/subscribers",
      subscription_url: "https://example.com/api/repo/subscription",
      commits_url: "https://example.com/api/repo/commits",
      git_commits_url: "https://example.com/api/repo/git/commits",
      comments_url: "https://example.com/api/repo/comments",
      issue_comment_url: "https://example.com/api/repo/issues/comments",
      contents_url: "https://example.com/api/repo/contents",
      compare_url: "https://example.com/api/repo/compare",
      merges_url: "https://example.com/api/repo/merges",
      archive_url: "https://example.com/api/repo/archive",
      downloads_url: "https://example.com/api/repo/downloads",
      issues_url: "https://example.com/api/repo/issues",
      pulls_url: "https://example.com/api/repo/pulls",
      milestones_url: "https://example.com/api/repo/milestones",
      notifications_url: "https://example.com/api/repo/notifications",
      labels_url: "https://example.com/api/repo/labels",
      releases_url: "https://example.com/api/repo/releases",
      deployments_url: "https://example.com/api/repo/deployments",
      created_at: "2023-10-25T00:00:00Z",
      updated_at: "2023-10-26T00:00:00Z",
      pushed_at: "2023-10-27T00:00:00Z",
      git_url: "https://example.com/api/repo/git",
      ssh_url: "git@example.com:repo.git",
      clone_url: "https://example.com/repo.git",
      svn_url: "https://example.com/repo/svn",
      homepage: "https://example.com/repo/home",
      size: 12345,
      stargazers_count: 6789,
      watchers_count: 9876,
      language: "JavaScript",
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      has_discussions: true,
      forks_count: 5432,
      mirror_url: "https://example.com/mirror",
      archived: false,
      disabled: false,
      open_issues_count: 100,
      license: {
        key: "custom_license",
        name: "Custom License",
        spdx_id: "123",
        url: "https://example.com/license",
        node_id: "node_id_license",
      },
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: true,
      topics: ["topic1", "topic2"],
      visibility: "public",
      forks: 321,
      open_issues: 123,
      watchers: 234,
      default_branch: "main",
    },
  ];
  

export const mockUser = {
    login: "testUser",
    id: 123,
    node_id: "2",
    avatar_url: "https://example.com/avatar.png",
    gravatar_id: "https://example.com/gravatar_id.png",
    url: "https://example.com/",
    html_url: "https://examplehtml.com/",
    followers_url: "https://example.com/followers",
    following_url: "https://example.com/following",
    gists_url: "https://example.com/gists_url",
    starred_url: "https://example.com/starred_url",
    subscriptions_url: "https://example.com/subscriptions_url",
    organizations_url: "https://example.com/organizations_url",
    repos_url: "https://example.com/repos_url",
    events_url: "https://example.com/events_url",
    received_events_url: "https://example.com/received_events_url",
    type: "user",
    site_admin: true,
    score: 24,
  };